version: '3.8'

services:
  developerevaluation.webapi:
    container_name: developer_evaluation_webapi
    image: ${DOCKER_REGISTRY-}developerevaluationwebapi
    build:
      context: .
      dockerfile: src/DeveloperEvaluation.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  developerevaluation.database:
    container_name: developer_evaluation_database
    image: postgres:17.0-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 30s
      timeout: 10s
      retries: 5      
    networks:
      - mais-q-um-dev-network

  developerevaluation.nosql:
    container_name: developer_evaluation_nosql 
    image: mongo:8.0    
    environment:
        MONGO_INITDB_ROOT_USERNAME: developer
        MONGO_INITDB_ROOT_PASSWORD: Develop@01
    ports:
      - "27017"

  developerevaluation.cache:
    container_name: developer_evaluation_cache 
    image: redis:7.4.1-alpine     
    command: redis-server --requirepass Develop@01
    ports:
       - "6379:6379"
     
  developerevaluation.rabbitmq:
    image: rabbitmq:3-management
    container_name: developer_evaluation_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_ERLANG_COOKIE: "mysecretcookie"
    networks:
      - rabbitmq-net
      
volumes:
  rabbitmq-data:
  postgresql:
  postgresql_data:
  
networks:
  rabbitmq-net:
  mais-q-um-dev-network:
    driver: bridge
    

    